version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pedido
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./script/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3.2
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      SERVICES: sqs, sns
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-2
    volumes:
      - ./script/localstack/init.sh:/etc/localstack/init/ready.d/init.sh

  app:
    build:
      context: .
    depends_on:
      - postgres
      - redis
      - localstack
    environment:
      AWS_REGION: us-east-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pedido
      DB_USER: root
      DB_PASSWORD: 123
      SNS_ORDER_RECEIVED_ARN: arn:aws:sns:us-east-2:000000000000:pedido-recebido
      SNS_ORDER_CONFIRMED_ARN: arn:aws:sns:us-east-2:000000000000:pedido-confirmado
      SQS_ORDER_PAYMENT_URL: http://localstack:4566/000000000000/pagamento-pedido
      SQS_ORDER_PRODUCTION_URL: http://localstack:4566/000000000000/producao-pedido
      CLOUD_AWS_ENDPOINT: http://localstack:4566
      REDIS_HOST: redis
    ports:
      - "8080:8080"