version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mikes-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./database/script/create-db.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mikes-db
      DB_SCHEMA: pedido
      DB_USER: root
      DB_PASSWORD: 123
    ports:
      - "8080:8080"
