version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pedido
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./database/script/create-db.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      AWS_REGION: us-east-2
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pedido
      DB_USER: root
      DB_PASSWORD: 123
      SNS_ORDER_RECEIVED_ARN: arn:aws:sns:us-east-2:000000000000:pedido-recebido
      SNS_ORDER_CONFIRMED_ARN: arn:aws:sns:us-east-2:000000000000:pedido-confirmado
      SQS_ORDER_PAYMENT_URL: http://localhost:4566/queue/pagamento-pedido
      SQS_ORDER_PRODUCTION_URL: http://localhost:4566/queue/producao-pedido
    ports:
      - "8080:8080"
