server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
  sql:
    init:
      platform: postgres

management:
  endpoints:
    web:
      exposure:
        include: health

sns:
  orderReceived:
    arn: ${SNS_ORDER_RECEIVED_ARN}
  orderConfirmed:
    arn: ${SNS_ORDER_CONFIRMED_ARN}

sqs:
  orderPayment:
    url: ${SQS_ORDER_PAYMENT_URL}
  orderProduction:
    url: ${SQS_ORDER_PRODUCTION_URL}