server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
  sql:
    init:
      platform: postgres

management:
  endpoints:
    web:
      exposure:
        include: health

sns:
  orderReceived:
    topicName: ${SNS_ORDER_RECEIVED_NAME}
  orderConfirmed:
    topicName: ${SNS_ORDER_CONFIRMED_NAME}

logging:
  level:
    io:
      awspring:
        cloud: DEBUG