server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
  sql:
    init:
      platform: postgres
  redis:
    host: ${REDIS_HOST}
    port: 6379
    timeout: 10000
  cache:
    redis:
      time-to-live: 5000

management:
  endpoints:
    web:
      exposure:
        include: health

cloud:
  aws:
    region:
      static: us-east-2
    credentials:
      accessKey: todoooooooo
      secretKey: todoooooooo
  elasticache:
    clusters:
      - name: mikes-redis-cluster
        expiration: 1000

sns:
  orderReceived:
    arn: ${SNS_ORDER_RECEIVED_ARN}
  orderConfirmed:
    arn: ${SNS_ORDER_CONFIRMED_ARN}

sqs:
  orderPayment:
    url: ${SQS_ORDER_PAYMENT_URL}
  orderProduction:
    url: ${SQS_ORDER_PRODUCTION_URL}